"""Initial check

Revision ID: 054075c31f8a
Revises: 
Create Date: 2023-09-28 22:05:29.592157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '054075c31f8a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'payments', ['payment_id'])
    op.alter_column('subscribes', 'date_start',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('subscribes', 'date_end',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'subscribes', ['subscribe_id'])
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'subscribes', type_='unique')
    op.alter_column('subscribes', 'date_end',
               existing_type=sa.DATETIME(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('subscribes', 'date_start',
               existing_type=sa.DATETIME(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_constraint(None, 'payments', type_='unique')
    # ### end Alembic commands ###
