"""add memo

Revision ID: 5b8675795bd8
Revises: 2a035f093ef4
Create Date: 2023-10-05 18:58:54.093732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b8675795bd8'
down_revision: Union[str, None] = '2a035f093ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memo',
    sa.Column('memo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sub_procedure_id', sa.Integer(), nullable=True),
    sa.Column('memo_text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['sub_procedure_id'], ['sub_procedures.sub_procedure_id'], ),
    sa.PrimaryKeyConstraint('memo_id'),
    sa.UniqueConstraint('memo_id')
    )
    op.create_unique_constraint(None, 'atlas', ['atlas_entry_id'])
    op.create_unique_constraint(None, 'atlas_photos', ['atlas_photo_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atlas_photos', type_='unique')
    op.drop_constraint(None, 'atlas', type_='unique')
    op.drop_table('memo')
    # ### end Alembic commands ###
