"""edit procedures v2

Revision ID: 6455bb3c305c
Revises: f2e0164b096b
Create Date: 2023-09-30 17:47:34.015376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6455bb3c305c'
down_revision: Union[str, None] = 'f2e0164b096b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_procedures',
    sa.Column('sub_procedure_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('procedure_id', sa.Integer(), nullable=True),
    sa.Column('procedure_subname', sa.Text(), nullable=False),
    sa.Column('procedure_code', sa.VARCHAR(length=255), nullable=False),
    sa.Column('procedure_description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['procedure_id'], ['procedures.procedure_id'], ),
    sa.PrimaryKeyConstraint('sub_procedure_id'),
    sa.UniqueConstraint('sub_procedure_id')
    )
    op.drop_column('procedures', 'procedure_description')
    op.drop_column('procedures', 'procedure_subname')
    op.drop_column('procedures', 'procedure_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedures', sa.Column('procedure_code', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('procedure_subname', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('procedures', sa.Column('procedure_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('sub_procedures')
    # ### end Alembic commands ###
