"""edit memo

Revision ID: 832b6f483fac
Revises: 5b8675795bd8
Create Date: 2023-10-07 16:04:07.635849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832b6f483fac'
down_revision: Union[str, None] = '5b8675795bd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memo_procedure',
    sa.Column('procedure_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('procedure_title', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('procedure_id', 'procedure_title'),
    sa.UniqueConstraint('procedure_id'),
    sa.UniqueConstraint('procedure_title')
    )
    op.add_column('memo', sa.Column('procedure_id', sa.Integer(), nullable=True))
    op.add_column('memo', sa.Column('memo_title', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'memo', ['memo_id'])
    op.drop_constraint('memo_sub_procedure_id_fkey', 'memo', type_='foreignkey')
    op.create_foreign_key(None, 'memo', 'memo_procedure', ['procedure_id'], ['procedure_id'])
    op.drop_column('memo', 'sub_procedure_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memo', sa.Column('sub_procedure_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'memo', type_='foreignkey')
    op.create_foreign_key('memo_sub_procedure_id_fkey', 'memo', 'sub_procedures', ['sub_procedure_id'], ['sub_procedure_id'])
    op.drop_constraint(None, 'memo', type_='unique')
    op.drop_column('memo', 'memo_title')
    op.drop_column('memo', 'procedure_id')
    op.drop_table('memo_procedure')
    # ### end Alembic commands ###
