"""added procedures

Revision ID: d99bed6395f7
Revises: 054075c31f8a
Create Date: 2023-09-30 17:41:20.201046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd99bed6395f7'
down_revision: Union[str, None] = '054075c31f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procedures',
    sa.Column('procedure_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('procedure_name', sa.Text(), nullable=False),
    sa.Column('procedure_code', sa.VARCHAR(length=255), nullable=False),
    sa.Column('procedure_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('procedure_id'),
    sa.UniqueConstraint('procedure_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedures')
    # ### end Alembic commands ###
