"""edit procedures

Revision ID: f2e0164b096b
Revises: d99bed6395f7
Create Date: 2023-09-30 17:43:10.221564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2e0164b096b'
down_revision: Union[str, None] = 'd99bed6395f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('procedures', sa.Column('procedure_subname', sa.Text(), nullable=False))
    op.create_unique_constraint(None, 'procedures', ['procedure_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'procedures', type_='unique')
    op.drop_column('procedures', 'procedure_subname')
    # ### end Alembic commands ###
